export const translations = {
  en: {
    // General
    appName: 'NSW Property Manager',
    search: 'Search...',
    save: 'Save',
    cancel: 'Cancel',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    areYouSure: 'Are you sure?',
    confirmDelete: 'This action cannot be undone.',
    yesDelete: 'Yes, delete it',
    noCancel: 'No, cancel',
    close: 'Close',
    exportToPdf: 'Export to PDF',
    exportToExcel: 'Export to Excel',
    viewAll: 'View All',
    back: 'Back',

    // Sidebar & Header
    dashboard: 'Dashboard',
    properties: 'Properties',
    ownerProfile: 'Owner Profile',
    adminPanel: 'Admin Panel',
    language: 'Language',
    role: 'Role',
    user: 'User',
    admin: 'Admin',
    
    // Dashboard
    dashboardTitle: 'Dashboard',
    welcomeBack: 'Welcome Back!',
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    total: 'Total',
    currentMonth: 'Current Month',
    manageProperties: 'Manage Properties',
    addIncome: 'Add Income',
    addExpense: 'Add Expense',
    totalProperties: 'Total Properties',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expense',
    netProfit: 'Net Profit',
    incomeVsExpense: 'Income vs. Expense',
    income: 'Income',
    expense: 'Expense',

    // Properties
    propertiesTitle: 'My Properties',
    addProperty: 'Add Property',
    editProperty: 'Edit Property',
    noProperties: 'No properties found. Click "Add Property" to get started.',
    noPropertiesDashboard: 'No properties yet. Add your first property to see it here.',
    propertyName: 'Property Name',
    propertyAddress: 'Property Address',
    propertyType: 'Property Type',
    propertyTypeHouse: 'House',
    propertyTypeShop: 'Shop',
    propertyTypeLand: 'Land',
    propertyTypeApartment: 'Apartment',
    propertyTypeCommercial: 'Commercial',
    selectType: 'Select a type',
    propertyPhotos: 'Property Photos',
    uploadPhotos: 'Upload Photos',
    dragAndDrop: 'Drag & drop files here, or click to select',
    photosPreview: 'Photos Preview',
    expectedRent: 'Expected Rent (Optional)',
    status: 'Status',
    statusVacant: 'Vacant',
    statusRented: 'Rented',
    flatShopNumberOptional: 'Flat / Shop Number (Optional)',
    
    // Property Detail
    propertyDetails: 'Property Details',
    totalOutstanding: 'Total Outstanding',
    tenant: 'Tenant',
    financialYear: 'Financial Year',
    finances: 'Finances',
    allYears: 'All Years',
    noIncomeFound: 'No Income Found',
    noExpenseFound: 'No Expense Found',
    documents: 'Documents',
    uploadDocument: 'Upload Document',
    noDocuments: 'No documents uploaded for this property.',
    documentName: 'Document Name',
    documentFile: 'Document File(s)',
    selectFile: 'Select file(s)',
    fileType: 'File Type',
    uploadedOn: 'Uploaded On',
    actions: 'Actions',
    view: 'View',
    download: 'Download',
    perMonth: '/Per month', 
    noTenant: 'This property is vacant.',
    tenantDocuments: 'Tenant Documents',
    
    // Transactions
    addTransaction: 'Add Transaction',
    editTransaction: 'Edit Transaction',
    noTransactions: 'No transactions recorded for this property.',
    transactionType: 'Transaction Type',
    transactionDescription: 'Description',
    transactionAmount: 'Amount',
    transactionDate: 'Date',
    selectTransactionType: 'Select type',
    property: 'Property',
    selectProperty: 'Select a property',
    amount: 'Amount',
    paymentMode: 'Payment Mode',
    selectPaymentMode: 'Select payment mode',
    paymentModeCash: 'Cash',
    paymentModeBank: 'Bank Transfer',
    paymentModeCard: 'Credit Card',
    dateReceived: 'Date Received',
    datePayment: 'Date of Payment',
    remarksOptional: 'Remarks (Optional)',
    attachProof: 'Attach Proof / Receipt / Bill',
    receiptsPreview: 'Receipts Preview',
    category: 'Category',
    selectCategory: 'Select a category',
    expenseCategoryDeprecation: 'Deprecation',
    expenseCategoryCleaningMaintenance: 'Cleaning/Maintenance',
    expenseCategoryTaxes: 'Taxes',
    expenseCategoryAutoAndTravel: 'Auto and Travel',
    expenseCategoryOther: 'Other',
    expenseCategoryRepairs: 'Repairs',

    // Tenant
    addTenant: 'Add Tenant',
    editTenant: 'Edit Tenant',
    tenantNameLabel: 'Name',
    mobile: 'Mobile',
    emailOptional: 'Email Id (Optional)',
    leaseStartDate: 'Did Start Date',
    leaseEndDate: 'Did End Date',
    leaseTerm: 'Lease Term (e.g., 12 months)',
    renewalDate: 'Renewal Date',
    leaseAmount: 'Rent Amount',
    paymentDueDay: 'Payment Due Day',
    depositOptional: 'Deposit (Optional)',
    rentInclusiveCharges: 'Rent-Inclusive Charges (Optional)',
    lightBill: 'Light Bill',
    governmentTaxes: 'Government Taxes',
    waterCharges: 'Water Charges',
    maintenanceCharges: 'Maintenance Charges',
    selectTenant: 'Select a Tenant',
    tenantPhoto: 'Tenant Photo',
    uploadDidDocument: 'Upload DID Document',
    didDocumentsPreview: 'DID Documents Preview',


    // Owner Profile
    ownerProfileTitle: 'Owner Information',
    ownerName: 'Full Name',
    ownerPhone: 'Phone Number',
    ownerEmail: 'Email Address',
    ownerAddress: 'Mailing Address',
    profileUpdated: 'Profile updated successfully!',
    ownerPhoto: 'Owner Photo',
    uploadPhoto: 'Upload Photo',
    changePhoto: 'Change Photo',
    removePhoto: 'Remove Photo',

    // Admin Panel
    adminPanelTitle: 'Admin Control Panel',
    allData: 'All Application Data',
    warningAdmin: 'You are in Admin mode. Changes made here can affect all data.',
  },
  bn: {
    // General
    appName: 'এনএসডব্লিউ প্রপার্টি ম্যানেজার',
    search: 'অনুসন্ধান করুন...',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    add: 'যোগ করুন',
    edit: 'সম্পাদনা',
    delete: 'মুছে ফেলুন',
    areYouSure: 'আপনি কি নিশ্চিত?',
    confirmDelete: 'এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।',
    yesDelete: 'হ্যাঁ, মুছে ফেলুন',
    noCancel: 'না, বাতিল করুন',
    close: 'বন্ধ করুন',
    exportToPdf: 'পিডিএফ এক্সপোর্ট',
    exportToExcel: 'এক্সেল এক্সপোর্ট',
    viewAll: 'সব দেখুন',
    back: 'পেছনে',

    // Sidebar & Header
    dashboard: 'ড্যাশবোর্ড',
    properties: 'সম্পত্তি',
    ownerProfile: 'মালিকের প্রোফাইল',
    adminPanel: 'অ্যাডমিন প্যানেল',
    language: 'ভাষা',
    role: 'ভূমিকা',
    user: 'ব্যবহারকারী',
    admin: 'অ্যাডমিন',

    // Dashboard
    dashboardTitle: 'ড্যাশবোর্ড',
    welcomeBack: 'আবারও স্বাগতম!',
    goodMorning: 'শুভ সকাল',
    goodAfternoon: 'শুভ অপরাহ্ন',
    goodEvening: 'শুভ সন্ধ্যা',
    total: 'মোট',
    currentMonth: 'চলতি মাস',
    manageProperties: 'সম্পত্তি পরিচালনা করুন',
    addIncome: 'আয় যোগ করুন',
    addExpense: 'ব্যয় যোগ করুন',
    totalProperties: 'মোট সম্পত্তি',
    totalExpense: 'মোট ব্যয়',
    netProfit: 'নীট লাভ',
    incomeVsExpense: 'আয় বনাম ব্যয়',
    income: 'আয়',
    expense: 'ব্যয়',

    // Properties
    propertiesTitle: 'আমার সম্পত্তি',
    addProperty: 'সম্পত্তি যোগ করুন',
    editProperty: 'সম্পত্তি সম্পাদনা',
    noProperties: 'কোনো সম্পত্তি খুঁজে পাওয়া যায়নি। শুরু করতে "সম্পত্তি যোগ করুন" ক্লিক করুন।',
    noPropertiesDashboard: 'এখনও কোনো সম্পত্তি নেই। এখানে দেখতে আপনার প্রথম সম্পত্তি যোগ করুন।',
    propertyName: 'সম্পত্তির নাম',
    propertyAddress: 'সম্পত্তির ঠিকানা',
    propertyType: 'সম্পত্তির ধরন',
    propertyTypeHouse: 'বাড়ি',
    propertyTypeShop: 'দোকান',
    propertyTypeLand: 'জমি',
    propertyTypeApartment: 'অ্যাপার্টমেন্ট',
    propertyTypeCommercial: 'বাণিজ্যিক',
    selectType: 'একটি ধরন নির্বাচন করুন',
    propertyPhotos: 'সম্পত্তির ছবি',
    uploadPhotos: 'ছবি আপলোড করুন',
    dragAndDrop: 'এখানে ফাইল টেনে আনুন, অথবা নির্বাচন করতে ক্লিক করুন',
    photosPreview: 'ছবির প্রিভিউ',
    expectedRent: 'প্রত্যাশিত ভাড়া (ঐচ্ছিক)',
    status: 'অবস্থা',
    statusVacant: 'খালি',
    statusRented: 'ভাড়া দেওয়া',
    flatShopNumberOptional: 'ফ্ল্যাট / দোকান নম্বর (ঐচ্ছিক)',

    // Property Detail
    propertyDetails: 'সম্পত্তির বিবরণ',
    totalOutstanding: 'মোট বকেয়া',
    tenant: 'ভাড়াটিয়া',
    financialYear: 'অর্থবছর',
    finances: 'আর্থিক বিবরণ',
    allYears: 'সব বছর',
    noIncomeFound: 'কোন আয় পাওয়া যায়নি',
    noExpenseFound: 'কোন ব্যয় পাওয়া যায়নি',
    documents: 'নথিপত্র',
    uploadDocument: 'নথি আপলোড করুন',
    noDocuments: 'এই সম্পত্তির জন্য কোনো নথি আপলোড করা হয়নি।',
    documentName: 'নথির নাম',
    documentFile: 'নথি ফাইল(গুলি)',
    selectFile: 'ফাইল(গুলি) নির্বাচন করুন',
    fileType: 'ফাইলের ধরন',
    uploadedOn: 'আপলোডের তারিখ',
    actions: 'ক্রিয়াকলাপ',
    view: 'দেখুন',
    download: 'ডাউনলোড',
    perMonth: '/ প্রতি মাস',
    noTenant: 'এই সম্পত্তিটি খালি।',
    tenantDocuments: 'ভাড়াটিয়ার নথিপত্র',

    // Transactions
    addTransaction: 'লেনদেন যোগ করুন',
    editTransaction: 'লেনদেন সম্পাদনা',
    noTransactions: 'এই সম্পত্তির জন্য কোনো লেনদেন রেকর্ড করা হয়নি।',
    transactionType: 'লেনদেনের ধরন',
    transactionDescription: 'বিবরণ',
    transactionAmount: 'পরিমাণ',
    transactionDate: 'তারিখ',
    selectTransactionType: 'ধরন নির্বাচন করুন',
    property: 'সম্পত্তি',
    selectProperty: 'একটি সম্পত্তি নির্বাচন করুন',
    amount: 'পরিমাণ',
    paymentMode: 'পেমেন্ট মোড',
    selectPaymentMode: 'পেমেন্ট মোড নির্বাচন করুন',
    paymentModeCash: 'নগদ',
    paymentModeBank: 'ব্যাঙ্ক স্থানান্তর',
    paymentModeCard: 'ক্রেডিট কার্ড',
    dateReceived: 'প্রাপ্তির তারিখ',
    datePayment: 'পেমেন্টের তারিখ',
    remarksOptional: 'মন্তব্য (ঐচ্ছিক)',
    attachProof: 'প্রমাণ / রসিদ / বিল সংযুক্ত করুন',
    receiptsPreview: 'রসিদ প্রিভিউ',
    category: 'বিভাগ',
    selectCategory: 'একটি বিভাগ নির্বাচন করুন',
    expenseCategoryDeprecation: 'অবচয়',
    expenseCategoryCleaningMaintenance: 'পরিষ্কার/রক্ষণাবেক্ষণ',
    expenseCategoryTaxes: 'কর',
    expenseCategoryAutoAndTravel: 'অটো এবং ভ্রমণ',
    expenseCategoryOther: 'অন্যান্য',
    expenseCategoryRepairs: 'মেরামত',

    // Tenant
    addTenant: 'ভাড়াটিয়া যোগ করুন',
    editTenant: 'ভাড়াটিয়া সম্পাদনা',
    tenantNameLabel: 'নাম',
    mobile: 'মোবাইল',
    emailOptional: 'ইমেইল আইডি (ঐচ্ছিক)',
    leaseStartDate: 'শুরুর তারিখ',
    leaseEndDate: 'শেষের তারিখ',
    leaseTerm: 'লীজের মেয়াদ (যেমন, ১২ মাস)',
    renewalDate: 'নবায়নের তারিখ',
    leaseAmount: 'ভাড়ার পরিমাণ',
    paymentDueDay: 'পেমেন্টের নির্ধারিত দিন',
    depositOptional: 'ডিপোজিট (ঐচ্ছিক)',
    rentInclusiveCharges: 'ভাড়া-অন্তর্ভুক্ত চার্জ (ঐচ্ছিক)',
    lightBill: 'লাইট বিল',
    governmentTaxes: 'সরকারি কর',
    waterCharges: 'পানি বিল',
    maintenanceCharges: 'রক্ষণাবেক্ষণ বিল',
    selectTenant: 'একজন ভাড়াটিয়া নির্বাচন করুন',
    tenantPhoto: 'ভাড়াটিয়ার ছবি',
    uploadDidDocument: 'ডিআইডি ডকুমেন্ট আপলোড করুন',
    didDocumentsPreview: 'ডিআইডি ডকুমেন্টের প্রিভিউ',
    
    // Owner Profile
    ownerProfileTitle: 'মালিকের তথ্য',
    ownerName: 'পুরো নাম',
    ownerPhone: 'ফোন নম্বর',
    ownerEmail: 'ইমেল ঠিকানা',
    ownerAddress: 'ডাক ঠিকানা',
    profileUpdated: 'প্রোফাইল সফলভাবে আপডেট করা হয়েছে!',
    ownerPhoto: 'মালিকের ছবি',
    uploadPhoto: 'ছবি আপলোড করুন',
    changePhoto: 'ছবি পরিবর্তন করুন',
    removePhoto: 'ছবি সরান',

    // Admin Panel
    adminPanelTitle: 'অ্যাডমিন কন্ট্রোল প্যানেল',
    allData: 'সমস্ত অ্যাপ্লিকেশন ডেটা',
    warningAdmin: 'আপনি অ্যাডমিন মোডে আছেন। এখানে করা পরিবর্তন সমস্ত ডেটাকে প্রভাবিত করতে পারে।',
  },
};